// ============================================================
// SentinelX — Firebase Options (PLACEHOLDER)
// ============================================================
// This file is auto-generated by `flutterfire configure`.
// DO NOT commit your real google-services.json to version control.
//
// SETUP INSTRUCTIONS:
//   1. Go to https://console.firebase.google.com
//   2. Create project → Add Android app
//   3. Package name: com.sentinelx.app
//   4. Download google-services.json → place in android/app/
//   5. Run: dart pub global activate flutterfire_cli
//   6. Run: flutterfire configure
//   7. This file will be replaced with real values.
// ============================================================

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not supported');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  // ⚠️  PLACEHOLDER VALUES — Replace with your real Firebase config
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_API_KEY',
    appId: 'YOUR_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId: 'YOUR_PROJECT_ID',
    storageBucket: 'YOUR_PROJECT_ID.appspot.com',
  );
}
